# Generated by Django 3.1.3 on 2020-11-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='slug',
            field=models.SlugField(default='s', unique=True),
            preserve_default=False,
        ),
    ]
