# Generated by Django 3.1.5 on 2021-01-06 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20201105_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.chapter'),
        ),
    ]
