# Generated by Django 3.1.5 on 2021-01-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_source_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
