# Generated by Django 3.1.5 on 2021-02-10 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_auto_20210125_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='is_movie',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('original_title', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True)),
                ('duration', models.IntegerField()),
                ('release_year', models.DateField()),
                ('genres', models.ManyToManyField(blank=True, null=True, to='video.Genre')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='video.Genre'),
        ),
        migrations.AddField(
            model_name='source',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.movie'),
        ),
    ]
