# Generated by Django 3.1.5 on 2021-02-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20210210_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='video.Genre'),
        ),
        migrations.AlterField(
            model_name='show',
            name='genres',
            field=models.ManyToManyField(blank=True, to='video.Genre'),
        ),
    ]
