# Generated by Django 3.1.5 on 2021-02-11 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_auto_20210210_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('slug', models.SlugField(unique=True)),
                ('information', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider')),
                ('button_text_action', models.CharField(blank=True, max_length=56, null=True)),
                ('url_action', models.CharField(blank=True, max_length=256, null=True)),
                ('type_slider', models.CharField(choices=[('P', 'POP UP'), ('R', 'Redirect'), ('N', 'Open New Link')], default='R', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.movie')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.show')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.slider')),
            ],
        ),
    ]
