# Generated by Django 3.1.5 on 2021-02-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_slider_slideritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideritem',
            name='type_slider_action',
            field=models.CharField(choices=[('P', 'POP UP'), ('R', 'Redirect'), ('N', 'Open New Link')], default='R', max_length=2),
        ),
        migrations.AlterField(
            model_name='slideritem',
            name='type_slider',
            field=models.CharField(choices=[('S', 'Show'), ('M', 'Movie'), ('IN', 'Information')], default='S', max_length=2),
        ),
    ]
