# Generated by Django 3.1.5 on 2021-02-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_auto_20210211_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideritem',
            name='order',
            field=models.IntegerField(default=5),
        ),
    ]
