# Generated by Django 3.1.5 on 2021-02-25 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0014_auto_20210224_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_source', models.CharField(max_length=1024)),
                ('type_source', models.CharField(choices=[('F', 'iFrame')], default='F', max_length=1)),
                ('active', models.BooleanField(default=True)),
                ('server', models.CharField(default='', max_length=128)),
                ('priority', models.IntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='is_short',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ShowSource',
            fields=[
                ('sourcebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='video.sourcebase')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.chapter')),
            ],
            bases=('video.sourcebase',),
        ),
        migrations.CreateModel(
            name='MovieSource',
            fields=[
                ('sourcebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='video.sourcebase')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.movie')),
            ],
            bases=('video.sourcebase',),
        ),
    ]
