# Generated by Django 3.1.5 on 2021-02-25 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0015_auto_20210225_0023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
    ]
