# Generated by Django 3.1.5 on 2021-02-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0017_movie_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
