# Generated by Django 3.1.5 on 2021-03-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0019_auto_20210309_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='ads_url',
            field=models.CharField(blank=True, default='', max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ads_url',
            field=models.CharField(blank=True, default='', max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='ads_url',
            field=models.CharField(blank=True, default='', max_length=56, null=True),
        ),
    ]
