# Generated by Django 3.1.5 on 2021-03-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0020_auto_20210309_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcebase',
            name='hls_source',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
