# Generated by Django 3.1.5 on 2021-04-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0021_sourcebase_hls_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcebase',
            name='label',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
