# Generated by Django 3.1.5 on 2021-04-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0023_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
