# Generated by Django 3.1.5 on 2021-04-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0024_collection_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='collection',
            field=models.ManyToManyField(blank=True, null=True, to='video.Collection'),
        ),
        migrations.AddField(
            model_name='show',
            name='collection',
            field=models.ManyToManyField(blank=True, null=True, to='video.Collection'),
        ),
    ]
